export const CHANGE_POPUP_CHAT = 'CHANGE_POPUP_CHAT';
export const CHANGE_POPUP_CHAT_SAGA = 'CHANGE_POPUP_CHAT_SAGA';
export const SET_USERS = 'SET_USERS';
export const SET_MESSAGE = 'SET_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
